replicaCount: 1
image:
  repository: ghcr.io/nrel-stratus-iac/aws-greengrass-docker
  tag: v2.5.4-r1
  pullPolicy: IfNotPresent
env:
- name: PROVISION
  value: "false"
envSecretRef: greengrass-v2-env
service:
  defaultPort: 8883
  altPort: 8443