apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    dav.release: {{ .Release.Name }}
    dav.chart: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: "default"
      port: {{ .Values.service.defaultPort }}
      targetPort: {{ .Values.service.defaultPort }}
    - name: "alt"
      port: {{ .Values.service.altPort }}
      targetPort: {{ .Values.service.altPort }}
  selector:
    dav.release: {{ .Release.Name }}
    dav.chart: {{ .Chart.Name }}
status:
  loadBalancer: {}
